### PR TITLE
Add new output targets: File and stdout

### PR DESCRIPTION
**Pull request by 7890**
```
oscsend --help
...
url     : specifies the destination parameters using a liblo URL.
          e.g. UDP        "osc.udp://localhost:9000"
               Multicast  "osc.udp://224.0.1.9:9000"
               TCP        "osc.tcp://localhost:9000"
               File       "file:///tmp/dump.osc"        <<< new
               stdout     -                             <<< new

Example:
oscsend - /hello sf "world?" .3 | hexdump -C
00000000  2f 68 65 6c 6c 6f 00 00  2c 73 66 00 77 6f 72 6c  |/hello..,sf.worl|
00000010  64 3f 00 00 3e 99 99 9a                           |d?..>...|
00000018
```

### CODE REVIEW

**Comment by 7890** [comment]
Some additional notes about the usecase:

-Use osc_send to assemble a message and then
 -use the serialized message to feed any other system (write to file, write to buffer, send to socket, encrypt, sign, base64 encode, ...)
 -use the serialized message to compare binary output of other OSC implementations for the same message
 -use the serialized message to send it repeatedly

Related:
I saw there is a new PR to add a function to the API to send serialized messages. This could be integrated to osc_send later so that osc_send can also send pre-created serialized messages.

**Comment by 7890** [comment]
@radarsat1 `osc_send` and `osc_dump` being separate programs is just fine, IMHO there is no benefit to merge them to one (it would probably just complicate CLI arguments parsing).

Related: It would be a small addition to `osc_dump` to pretty-print serialized OSC blobs from a file or stdin analog to this PR.

**Comment by radarsat1** [comment]
I should start breaking off the discussion to some wishlist items ;)

> It would be a small addition to osc_dump to pretty-print serialized OSC blobs from a file or stdin analog to this PR.

It's been my opinion for a long time that it's really a shame there is no "official" text representation for OSC.  Perhaps liblo could show some leadership in that respect, but some discussion on the OSC mailing list would be warranted before starting to create a "file format".

**Comment by radarsat1** [comment]
Hm, actually it seems that mailing list is no longer alive, I'm not even sure whether the best public place to discuss these things is right now.

**Comment by radarsat1** [comment]
In any case, I'll just jot down a few ideas while they are in my head.

The thing about supporting a file format is that it needs more than just raw representation of the messages to be useful for logging and playback.  At a bare minimum, unless we want to "send them all at once", it must support timestamps, which is already supported, but it should be recognized that this is no longer raw OSC, but is an addition to OSC's bundles which are the only way OSC supports timestamps.

That sort of takes care of time, but then there is place.  Where to send the messages.  If one destination, it could be specified on the command line and we are done.  But what if we want to record and playback multiple sources and destinations?  Things start to get a little more complicated.

I can imagine having destination IDs in the file, in the form of URLs, something like:

```
[1] osc.udp://somehostname:9000
[2] osc.tcp://anotherhost:9001
to [1]: <timestamp> /my/message iii 1 2 3
...`

etc.. something like that.  Maybe the destinations can be overridden by command-line arguments.

Of course, anything beyond that, beyond timed sending and receiving with multiple sources and destinations, may be more difficult to represent in a file, for instance interactive situations, queries etc, there is no way to avoid doing it with a script/program.  But I'm trying to think if there are any other important considerations on the file format side of things..

Lastly there is binary vs text.  Ideally both should be supported and a tool to convert between them.  As for binary representations, now you are mixing data types, eg. destination indicators, timestamps, and messages.  MIDI files are basically just dumps of MIDI messages prepended by time intervals.  Can we do better? How to handle "framing" in a sane and useful manner?

Liblo TCP streams support two framing mechanisms, length-prefix and SLIP streams.  This could translate to files, but doesn't allow easy random access... if that's important.

As for text representation, should we keep using something ad-hoc, or go to some standard format like JSON or XML?

These are several questions nagging at me as oscdump and oscsend get more development attention..

@malloch any opinions?  :)  or on where (what forum) to take this discussion...?

**Comment by radarsat1** [comment]
>  IMHO there is no benefit to merge them to one (it would probably just complicate CLI arguments parsing).

Imagine the OSC equivalent of "tee" or "netcat"/"socat".. accept messages on one port, re-send them to another port, while writing them to a local file.  This would be incredible useful for debugging OSC applications.

**Comment by radarsat1** [comment]
By the way, more specific to this issue,

> -Use osc_send to assemble a message and then
> -use the serialized message to feed any other system (write to file, write to buffer, send to socket, encrypt, sign, base64 encode, ...)
> -use the serialized message to compare binary output of other OSC implementations for the same message
> -use the serialized message to send it repeatedly

I agree that all this appears very useful, and seeing the raw bytes through hexdump for sure, but much less useful than it would be if messages are timestamped.  Time information is critical for using OSC.  However this requires injecting non-sent non-OSC metadata into the serialized stream.  The files that oscdump writes right now already have this ad-hoc format of a (non-human readable!) hex representation of the timestamp before each message, but this doesn't appear in any other place, e.g. TCP streams, or anywhere.  If one were to do `oscsend - <multiple messages> | oscdump -` they would all get written with the same timestamp.  So oscsend supporting multiple messages would already *require* some handling of "time" -- which is worth some careful consideration imho.

**Comment by radarsat1** [comment]
For instances, should we aim to have something like this work?

```
oscsend - <multiple, timed messages> | oscdump - | oscsend osc.udp://destination -
```

**Comment by 7890** [comment]
Indeed some interesting ideas floating around!
Continuing the brain dump, there are many formats that can make sense for an OSC message. The only one defined by the standard is AFAIK the binary format. JSON: everybody cooks something else (seemingly every other JS binary OSC parser invents a new JSON representation for it). XML: another candidate. Optimally conversions would be lossless, without ambiguity from each to the other format. It would be wishful to have official formats on how to express OSC in JSON and XML at some point in time.
One global thought is that OSC can be useful as a content format, without anything else attached. Defined conversions to other formats and tools are an almost logical consequence.
osc_send and osc_dump are the prototypes for I/O. I was thinking about timestamps too, how to append binary messages to a file (eventually framed in a blob for size indication) etc. etc. but I thought let's start off simple. Serializing a single message can be useful already. Timestamps are not relevant for every case but for a serious recording and replay it's necessary to have. For record/playback to/from file, please also see https://github.com/OpenMusicKontrollers/oscfile which does exactly that. This guy also has a few other interesting OSC apps. OSC is great since it's an exactly defined format, no complicated stuff attached, not constantly changing, well suited for real-time messaging (but not limited to). Extending it to JSON and XML to represent any valid OSC message will make it even more versatile and web-friendly, but it needs the same well-thought-through approach as for the binary spec.

**Comment by radarsat1** [comment]
Thanks @7890 for your thoughts, I agree on all points.  Yes, I think serializing a single message this way is already useful, I guess hesitation regarding timestamps is only relevant to supporting multiple messages.  In the meantime I think the feature proposed in this PR is not a bad idea.

In the future handling multiple messages and whether/how timestamps are included etc can perhaps be handled by command line parameters, but I see no reason not to integrate this simple stdout idea for a *single message* already.

**Comment by 7890** [comment]
we have bytes on stdout :) Thanks Stephen!

**Comment by 7890** [comment]
> Liblo TCP streams support two framing mechanisms, length-prefix and SLIP streams. This could translate to files, but doesn't allow easy random access... if that's important.

A test (sometime back) with a small header for messages that allow for a doubly-linked-list style navigation in a file showed that it's almost comparable to database speed for accessing any message.
The length-prefix method is the most simple. SLIP has it's own beauty as being a simplistic chunked stream..

**Comment by radarsat1** [comment]
That makes me wonder if a small database like sqlite might actually be a useful solution here.
I think there was some previous work on testing recording of OSC messages to B-tree databases (I think postgres was used) and shown to be quite efficient.  Then, piggy-backing off such a system to generate XML/JSON/csv/whatever could be trivial.  Don't know if it's worth the extra dependency but it could be an interesting direction to research.  (sqlite at least is quite easily available)

Speaking of SLIP and other methods, I also wondered about directly supporting websockets, since it comes with its own packetization protocol.  But maybe its best kept as a transport-layer protocol and not used to dilinear OSC messages themselves.

**Comment by 7890** [comment]
That brings us to another format/container to consider, which is SQL, eg. one record per message. sqlite seems an easy start. I find that using just OSC mechanisms can also be interesting (using what's available), say for record sets of up to a few 100k messages.

Websockets - yes, it's something that screams to push OSC through :) From my few experiments, it's a bit hairy to make it work with a session, the HTTP/WS switch, make it useful through HTTPS etc. It's very interesting for OSC but maybe not as a bult-in facility for liblo. However a known scenario on how to easily hook up liblo with an WS library would be useful (eg. a just a C program, no node.js involved).

**Pull request merged**
