### PR TITLE
Removal of pthreads from MSVC build and use of native threads instead

### PR DESCRIPTION
**Pull request by stekyne**
Hi again!

Decided that including pthreads on Windows is a pain so why not remove it altogether. There isn't really that much code to change anyways.

This is a preliminary review I guess. I need to test it a bit more but I think it looks fairly resonable.
Let me know what you think!

### CODE REVIEW

**Comment by radarsat1** [comment]
Oh wow something I've wanted to do forever.  I'll take a look!

**Comment by stekyne** [comment]
I got some of the code examples from: https://locklessinc.com/articles/pthreads_on_windows/. Which is what the libpthreads for windows implementation is based on. So it should be sound.

**Comment by stekyne** [comment]
Any update on this? Did you manage to take a look yet?

**Comment by radarsat1** [comment]
I haven't been able to get my hands on a Windows development machine.  However the patch seems well-implemented from what I can see. It did break the Linux build for me so I'll fix that and apply it.

**Comment by radarsat1** [comment]
Can you please test master and let me know if I broke anything with regards to CMake/Visual Studio?  Thank you.  I added support for your changes to MingW, seems to work when compiled using mingw under Linux so I want to make sure I didn't mess up your PR while doing so.

**Comment by stekyne** [comment]
I'll test it today cheers

**Pull request merged**
