### PR TITLE
quit oscdump properly

### PR DESCRIPTION
**Pull request by malloch**
patch to quit the oscdump tool properly, allowing the output to be piped to file

### CODE REVIEW

**Comment by smlz** [comment]
@malloch: Oh, this saved my day! Or night.

Sorry, but I have to vent a bit. I just spent an *entire* night trying to get a script to read from oscdump's output. And I _seriously_ started to question my somewhat mediocre intelligence.

At one point I found this nine year old thread (http://osc_dev.create.ucsb.narkive.com/hsFpkGwe/no-dumposc-output-in-pipe-in-non-interactive-terminal) with two dozens of messages, and an idiot with five academic titles, who continuously tries to argue that the behaviour of oscdump is perfectly fine.

Sorry for the rant, and @radarsat1: +1 for applying this pull request

**Comment by radarsat1** [comment]
To be fair, the dumpOSC tool discussed in that thread is a different tool from the original OSC implementation by Matt Wright. Confusingly, liblo's tool is called dumposc and is a different program. Sorry for not merging this more recently.. I haven't looked at liblo in a little while.  It needs to be rebased, but I can do that if @malloch doesn't get around to it.

I'm not sure which idiot you're referring to in that thread, but some of the posts are from me, stating that I'm able to read the output of dumpOSC just fine.  It probably depends on the platform, which you neglected to mention.

If you're referring to Angelo Fraietta's comments, since he has all the academic titles listed, he seems to be only pointing out that the OP is trying to make an example program work like a standard Unix tool, instead of just taking it as an example and modifying it to suit him.  Seems reasonable to me.  But let's not discuss old things.

The bigger issue here is that both oscdump and dumpOSC were not designed to output machine readable data, and therefore were never really tested for this purpose.  I've long thought an OSC-text translation standard should be available.  liblo's oscdump and oscsend would be perfect candidates to implement such a thing if you want to take a shot at it.  Say, some kind of OSC-to-JSON-and-back test case. (or XML, or YAML.., or..)

**Comment by radarsat1** [comment]
Rebased in 3ba44881404b90e545eae3bb4f6139d37933d548

**Comment by smlz** [comment]
Thanks for merging the fix. And hey, I had to let off some steam... :sob:
And to be fair, it is not all the author's fault, because only a language like C can lead to such problems. 

About your suggestion, I think oscdump is a simple but nonetheless very useful tool to integrate OSC within larger systems. For us the simplest solution is just piping it's output into a little helper script, that than forwards the messages we're interested in to OSC-incompatible systems, across firewalls, etc...

**Comment by radarsat1** [comment]
I understand. No worries.

> And to be fair, it is not all the author's fault, because only a language like C can lead to such problems.

Actually it's not really C.. as such.  Well, it is related to libc.  The problem is more a file handle thing -- the output is buffered.   Another way to solve the problem (for almost any program) is to use a program that disables output buffering: 

    stdbuf -oL oscdump 9000 | my_script.sh

Not tested, but I'm pretty sure this would allow all data to end up being read even if the program receives SIGINT (Ctrl-C).  Another solution would be to insert fflush() commands after printf() in oscdump.

**Comment by smlz** [comment]
Ha, thanks for the stdbuf trick! Works like a charm. Didn't know that.

I thought I tried the fflushf(), and was astonished that it did not work, but it was probably just too late...

**Comment by radarsat1** [comment]
I'd be surprised if it didn't, but I could be wrong!

**Comment by smlz** [comment]
It does! I tried it now again and it worked. Anyway, thanks for the good advice.

**Comment by smlz** [comment]
I decided to add this one fflush(stdout) to oscdump.c. Doesn't hurt, does it?!

Btw, here is a nice explanation on stackoverflow of how standard output gets buffered, or not, in different standard C libraries: http://stackoverflow.com/a/13933741

**Pull request closed without merging**
