### PR TITLE
automake projects lacking README are "foreign"

### PR DESCRIPTION
**Pull request by umlaeute**
the GNU standard dictates the existence of a "README" file, so automake refuses to work if this file is missing.

since we have a `README.md` (but no `README`), we have basically two options:
- create a dummy `README` file (by copying, symlinking,... the `README.md`)
- tell `automake` that we are *not strictly* following the GNU standards by flagging this project as `foreign`.

i think the first (and current) choice is cruft, as it needlessly clutters my filesystem with yet more files.
so this PR implements the second option.

### CODE REVIEW

**Comment by radarsat1** [comment]
But the copied README is what gets packed into the tarball during make dist...

**Comment by umlaeute** [comment]
so there's two READMEs? one for the devs (`README.md`) and one for the users (`README`)?
and both have the same content?

sounds like confusion to me. (I'd rather ship `README.md` to the users as well).

**Comment by umlaeute** [comment]
(but of course: if you don't think it's worth it, just close this PR)

**Comment by radarsat1** [comment]
Actually they are the same file (hard link).  The history is that there was README, but when I moved the project to github I looked for a way to tell github that it was a markdown file, but github requires the .md extension.  So I just renamed it, but copied it back to satisfy automake.  (I have always worked under the assumption that extra files would not bother developers much, and users should be using the tarball, avoiding this confusion you mention.  however lately it seems that users use github directly, so now upstream developers need to consider the user friendliness of the development environment.. this is a new state of affairs.)

So in any case, if you think it's sufficiently confusing we can change it, at the "expense" that the project no longer follows "GNU standards" according to automake.  I suppose there's no explicit reason to follow it.

**Pull request closed without merging**
